version: '3.8'

services:
  mbits:
    container_name: mbits-nginx
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_PROXY_SERVER: ${MBITS_PROXY_SERVER_URL:-http://localhost:8090}
    ports:
      - '8089:80'
    restart: unless-stopped
    networks:
      - mbits

  proxy-server:
    image: ghcr.io/danvergara/jumble-proxy-server:latest
    environment:
      - ALLOW_ORIGIN=${MBITS_SOCIAL_URL:-http://localhost:8089}
      - MBITS_PROXY_GITHUB_TOKEN=${MBITS_PROXY_GITHUB_TOKEN}
      - ENABLE_PPROF=true
      - PORT=8080
    ports:
      - '8090:8080'
    networks:
      - mbits

networks:
  mbits:
